version: '3.5'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:4000'
    stdin_open: true

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
