version: '3.5'

services:
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - '4000:4000'
  #   stdin_open: true

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"

  google-map:
    build: 
      context: ./backend-v2
      dockerfile: ./apps/google-map/Dockerfile
      target: development
    command: pnpm run start:dev google-map
    ports:
      - '3000:3000'  # container : host machine
    volumes:
      - ./backend-v2:/app  # machine : container
    container_name: google-map
    stdin_open: true
